debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

# redirect HTTP -> HTTPS, install certificates
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/certs/server.crt"
      keyFile = "/etc/certs/server.key"

# activating docker API
[docker]
domain = "docker.local"
watch = true

# activate traefik dashboard
[api]
  [api.statistics]
    recentErrors = 10